# Generated by Django 5.1.15 on 2026-09-18 17:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do cliente', max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail de contato do cliente', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Telefone de contato do cliente', max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do vendedor', max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail corporativo ou de contato do vendedor', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Telefone de contato do vendedor', max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='0 para Segunda-feira até 6 para Domingo', unique=True, verbose_name='Dia da Semana')),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Piso de comissão permitido para o dia (0.00% a 10.00%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Percentual Mínimo (%)')),
                ('max_percentage', models.DecimalField(decimal_places=2, help_text='Teto de comissão permitido para o dia (0.00% a 10.00%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Percentual Máximo (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Regra de Comissão por Dia',
                'verbose_name_plural': 'Regras de Comissão por Dia',
                'ordering': ['day_of_week'],
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='check_valid_day_of_week'), models.CheckConstraint(condition=models.Q(('min_percentage__gte', Decimal('0.00')), ('min_percentage__lte', Decimal('10.00'))), name='check_min_commission_range'), models.CheckConstraint(condition=models.Q(('max_percentage__gte', Decimal('0.00')), ('max_percentage__lte', Decimal('10.00'))), name='check_max_commission_range'), models.CheckConstraint(condition=models.Q(('min_percentage__lte', models.F('max_percentage'))), name='check_min_lte_max_commission')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código identificador único do produto (SKU)', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(help_text='Descrição detalhada do produto', max_length=255, verbose_name='Descrição')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço unitário em reais, estritamente positivo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário (R$)')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Percentual nominal cadastrado entre 0.00% e 10.00%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Percentual de Comissão Padrão (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o produto está ativo para novas vendas', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['description'],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='check_product_unit_price_positive'), models.CheckConstraint(condition=models.Q(('commission_percentage__gte', Decimal('0.00')), ('commission_percentage__lte', Decimal('10.00'))), name='check_product_commission_range')],
            },
        ),
    ]
