# Generated by Django 5.1.15 on 2026-09-18 17:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Identificador único da nota fiscal informado manualmente', max_length=50, unique=True, verbose_name='Número da Nota Fiscal')),
                ('sold_at', models.DateTimeField(db_index=True, help_text='Data e hora em que a venda foi realizada', verbose_name='Data e Hora da Venda')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total da Venda (R$)')),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Comissão (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer', verbose_name='Cliente')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.salesperson', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-sold_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade de itens vendidos (mínimo 1)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Valor unitário congelado no momento da venda', max_digits=12, verbose_name='Preço Unitário (R$)')),
                ('applied_commission_percentage', models.DecimalField(decimal_places=2, help_text='Percentual efetivo após delimitação pelas regras do dia', max_digits=5, verbose_name='Percentual de Comissão Aplicado (%)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Subtotal do item (quantidade * preço unitário)', max_digits=12, verbose_name='Valor Total do Item (R$)')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Comissão gerada pelo item', max_digits=12, verbose_name='Valor da Comissão (R$)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='sales.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='check_sale_item_quantity_positive')],
            },
        ),
    ]
